---
- name: Check if swap file already exists
  ansible.builtin.stat: path={{ swap_path }}
  register: swapfile

- name: Create a swap file
  ansible.builtin.shell: fallocate -l {{ swap_size }} {{ swap_path }}
  when: swapfile.stat.exists == False

- name: Change permissions of swap file
  ansible.builtin.file:
    path: "{{ swap_path }}"
    state: file
    owner: root
    group: root
    mode: 0600
  when: swapfile.stat.exists == False

- name: Setup swap space
  ansible.builtin.shell: mkswap {{ swap_path }}
  when: swapfile.stat.exists == False

- name: Enable swap space
  ansible.builtin.shell: swapon {{ swap_path }}
  when: swapfile.stat.exists == False

- name: Configure swapiness
  ansible.builtin.sysctl:
    name: vm.swappiness
    value: "{{ swap_swappiness }}"
    state: present
  when: swapfile.stat.exists == False

- name: Configure vfs_cache_pressure
  ansible.builtin.sysctl:
    name: vm.swappiness
    value: "50"
    state: present
  when: swapfile.stat.exists == False

- name: Manage swap file in /etc/fstab
  ansible.builtin.mount:
    src: "{{ swap_path }}"
    name: "none"
    fstype: "swap"
    opts: "sw"
    dump: "0"
    passno: "0"
    state: present
  when: swapfile.stat.exists == False
